name: ci

on: [push, pull_request]

jobs:
  build:
    name: xhr tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 2
      - name: check formatting
        run: deno fmt --check
      - name: check linting
        run: deno lint
      - name: run tests
        run: deno task test
